version: '3'
services:
    selenium-hub:
        image: selenium/hub
        container_name: selenium-hub
        ports:
          - "4444:4444"
        environment:
        - GRID_MAX_SESSION=2
        - GRID_BROWSER_TIMEOUT=30000
        - GRID_TIMEOUT=90000
    chrome:
        image: selenium/node-chrome
        depends_on:
          - selenium-hub
        environment:
          - HUB_HOST=selenium-hub
          - HUB_PORT=4444