version: '3'
services:
    selenium-hub:
        image: selenium/hub
    chrome:
        image: selenium/node-chrome
        depends_on:
          - selenium-hub
        environment:
          - HUB_HOST=selenium-hub
          - HUB_PORT=4444
        volumes:
          - /dev/shm:/dev/shm
    test-runner:
        build:
          context: .
        depends_on:
        - selenium-hub
        - chrome